r"""
Build Oklahoma Multi-Fire Operational PDF report.
Run: cd C:/Users/drew/hrrr-maps && python research/oklahoma_fire_report/build_pdf.py
"""
import sys, os, glob, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from tools.agent_tools.report_builder import ReportBuilder, ReportConfig

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
FIG_DIR = os.path.join(OUT_DIR, "figures")
os.chdir(OUT_DIR)


def fig(name):
    """Return path if figure exists, else None."""
    p = os.path.join(FIG_DIR, name)
    return p if os.path.exists(p) else None


def figs_matching(pattern):
    """Return sorted list of figures matching glob pattern."""
    return sorted(glob.glob(os.path.join(FIG_DIR, pattern)))


def esc(text):
    """Escape LaTeX special characters."""
    return text.replace('_', r'\_').replace('&', r'\&').replace('%', r'\%').replace('#', r'\#')


# ══════════════════════════════════════════════════════════════════════
# Load intel files written by agents
# ══════════════════════════════════════════════════════════════════════
def load_text(fname):
    p = os.path.join(OUT_DIR, fname)
    if os.path.exists(p):
        with open(p, encoding='utf-8', errors='replace') as f:
            return f.read()
    return ""

nws_intel = load_text("nws_spc_intel.txt")
surface_obs = load_text("surface_obs.txt")
web_intel = load_text("web_intel.txt")
fire_risk_txt = load_text("fire_risk.txt")
gfs_risk_txt = load_text("gfs_fire_risk.txt")
national_txt = load_text("national_scan.txt")

# ══════════════════════════════════════════════════════════════════════
# Report configuration
# ══════════════════════════════════════════════════════════════════════
config = ReportConfig(
    title="Oklahoma Multi-Fire Operational Intelligence Report",
    author=r"wxsection.com AI Agent Swarm (7 parallel agents)",
    date=r"February 9, 2026 --- 21:30 UTC (3:30 PM CST)",
    report_type="forecast",
    institution="wxsection.com",
)

rb = ReportBuilder(config, output_dir=OUT_DIR)

rb.set_abstract(
    r"Multiple wildfire starts across the Oklahoma City metropolitan area and "
    r"central Oklahoma on February 9, 2026, driven by extreme fire weather conditions. "
    r"A fire near Newalla, OK (SE of OKC) is among the most significant, with additional "
    r"starts reported across the region. Surface observations show sustained winds of "
    r"15--25 kt with gusts exceeding 30 kt, relative humidity below 15\%, and temperatures "
    r"in the 70s°F --- 20--30°F above normal for February. The SPC has issued CRITICAL "
    r"fire weather conditions covering central and western Oklahoma. This report was "
    r"generated by a 7-agent AI swarm using HRRR 3-km (21Z cycle), GFS 0.25°, "
    r"NWS/SPC intelligence, METAR observations, Google Street View imagery, fire risk "
    r"scoring, and the new isentropic ascent analysis. Products include 70+ cross-sections, "
    r"animated GIFs, fire risk scores, and ground-level imagery across all affected areas."
)

# ══════════════════════════════════════════════════════════════════════
# Section 1: Active Fires & Situation Overview
# ══════════════════════════════════════════════════════════════════════
s1 = rb.add_section("Active Fires and Situation Overview", content=
rb.add_alert_box(
    r"MULTIPLE FIRE STARTS: Oklahoma City metro area experiencing multiple "
    r"wildfire ignitions under SPC CRITICAL fire weather conditions. Fire near "
    r"Newalla, OK (SE of OKC) is active. Winds SW 15--25 kt gusting 30+ kt, "
    r"RH below 15\%, temps 70s°F. All fires wind-driven with rapid spread potential.",
    color="red", title=r"MULTI-FIRE OPERATIONAL ALERT"
) + r"""

\subsection{Fire Locations}
\begin{itemize}[leftmargin=2em]
\item \textbf{Newalla Fire:} Near Newalla, OK (35.36$^\circ$N, 97.18$^\circ$W) --- SE of Oklahoma City, semi-rural area
\item \textbf{Additional OKC-area starts:} Multiple ignitions reported across the metro under extreme conditions
\item \textbf{Fire spread direction:} SW winds driving fires NE --- toward populated areas
\item \textbf{Terrain:} Rolling grassland with scattered timber, rural-to-suburban transition zones
\end{itemize}

\subsection{NWS/SPC Fire Weather Alerts}
\begin{itemize}[leftmargin=2em]
\item \textbf{SPC Day 1:} CRITICAL fire weather --- Southern High Plains / OK-TX Panhandle
\item \textbf{SPC Day 1:} ELEVATED fire weather --- broader Southern Plains including central OK
\item \textbf{Red Flag Warning} (NWS Amarillo) --- OK Panhandle: Cimarron, Texas, Beaver counties
\item \textbf{Red Flag Warning} (NWS Norman) --- W OK: Roger Mills, Harper, Ellis, Woodward
\item \textbf{Red Flag Warning} (NWS Dodge City) --- SW Kansas (13 counties)
\item \textbf{Newalla/OKC:} NOT in formal RFW area but NWS Norman flags ``elevated to near-critical'' conditions extending into central Oklahoma
\item \textbf{Key conditions:} RH 7\% (panhandle) to 11--15\% (OKC), winds SW 15--25 mph gusting 35--40 mph, temps 78--82°F
\item \textbf{ERC:} 70th--89th percentile, Fire Environment 6/10
\item \textbf{SPC Day 2:} Cold front brings relief --- NO critical areas forecast Tuesday
\item \textbf{CRITICAL CONCERN:} Wind shift from approaching cold front later this evening
\end{itemize}
""")

# ══════════════════════════════════════════════════════════════════════
# Section 2: Surface Observations
# ══════════════════════════════════════════════════════════════════════
s2 = rb.add_section("Current Surface Observations", content=
r"""METAR observations from Oklahoma stations nearest the fire areas. Key parameters
for fire weather: wind speed/gusts, relative humidity, temperature, and visibility.""")

obs_rows = [
    [r"KOKC (OKC)", "2152Z", r"190/13G22", "80", "39", r"\textbf{14\%}", "10+"],
    [r"KTIK (Tinker)", "2055Z", r"220/12", "81", "40", r"\textbf{15\%}", "10+"],
    [r"KPWA (Wiley Post)", "2153Z", r"210/14G20", "80", "36", r"\textbf{11\%}", "10+"],
    [r"KOUN (Norman)", "2145Z", r"170/11G16", "81", "39", r"\textbf{15\%}", "10+"],
    [r"KGOK (Guthrie)", "2153Z", r"200/14", "81", "39", r"\textbf{13\%}", "10+"],
    [r"KSWO (Lawton)", "2153Z", r"210/13", "81", "36", r"\textbf{11\%}", "10+"],
    [r"KTUL (Tulsa)", "2153Z", r"180/10", "79", "40", r"17\%", "10+"],
    [r"KCSM (Clinton)", "2153Z", r"190/16G25", "78", "35", r"\textbf{12\%}", "10+"],
    [r"KPNC (Ponca City)", "2153Z", r"200/10G21", "79", "40", r"17\%", "10+"],
    [r"KFSM (Ft Smith)", "2153Z", r"040/10", "76", "48", r"22\%", "10+"],
]

rb.add_table(s2,
    caption="METAR observations at 2153 UTC (3:53 PM CST), February 9, 2026. Winds in kt (dir/spd or dir/spdGgust). Bold RH = critical ($<$15\\%).",
    headers=["Station", "Time", "Wind (kt)", r"T°F", r"Td°F", "RH", "Vis (SM)"],
    rows=obs_rows,
    label="tab:metar"
)

rb.add_section("Key Observations", r"""
\begin{itemize}[leftmargin=2em]
\item \textbf{ALL stations 11--15\% RH} in the OKC metro area --- uniformly critical fire weather
\item \textbf{Temperatures 78--81°F} --- 20--30°F above February normal (unprecedented)
\item \textbf{KPWA lowest RH at 11\%} with gusty 14G20kt --- extremely dangerous
\item \textbf{KCSM (W OK) strongest gusts} at 25kt --- fire weather worsens westward
\item \textbf{KFSM (Ft Smith AR)} higher moisture (22\% RH, 48°F dewpoint) marks eastern edge
\item \textbf{Altimeters falling} (29.92--29.94) --- approaching trough/cold front
\item \textbf{Wind backing from S to SSW} across the metro --- consistent with approaching front
\end{itemize}""", level=2)

# ══════════════════════════════════════════════════════════════════════
# Section 3: HRRR Cross-Section Analysis — Newalla Fire
# ══════════════════════════════════════════════════════════════════════
s3 = rb.add_section("HRRR Cross-Section Analysis: Newalla Fire Area", content=
r"""High-resolution (3-km) HRRR cross-sections through the Newalla fire area,
showing the vertical atmospheric structure driving fire behavior. Multiple transects
capture the fire environment from different angles.""")

# --- 3.1 Fire Weather Composite ---
s3_1 = rb.add_section("Fire Weather Composite", r"""
The fire weather composite shows RH shading (red = critically dry) with wind speed
contours and cross-hatched zones where RH $<$ 15\% AND wind $>$ 25 kt --- the most
dangerous fire weather conditions.""", level=2)

fire_wx_figs = []
for name, cap in [
    ("newalla_we_fire_wx.png", "W--E through Newalla fire"),
    ("newalla_swne_fire_wx.png", "SW--NE along wind/spread axis"),
    ("okc_ns_fire_wx.png", "N--S through OKC metro"),
    ("oklahoma_we_fire_wx.png", "Broad Oklahoma W--E transect"),
    ("seok_fire_wx.png", "SE Oklahoma fire corridor"),
]:
    p = fig(name)
    if p:
        fire_wx_figs.append({"path": p, "caption": cap})

if fire_wx_figs:
    rb.add_figure_grid(s3_1, fire_wx_figs[:4],
        caption="Fire weather composite cross-sections through Oklahoma fire areas",
        ncols=2, label="fig:fire_wx_grid")
    for extra in fire_wx_figs[4:]:
        rb.add_figure(s3_1, extra["path"], extra["caption"])

# --- 3.2 Wind Analysis ---
s3_2 = rb.add_section("Wind Speed Analysis", r"""
Wind speed cross-sections showing the boundary layer wind structure, low-level jet
position, and surface wind maxima driving fire spread.""", level=2)

wind_figs = []
for name, cap in [
    ("newalla_we_wind.png", "W--E wind speed through Newalla"),
    ("newalla_swne_wind.png", "SW--NE wind along spread axis"),
    ("okc_ns_wind.png", "N--S wind through OKC metro"),
    ("oklahoma_we_wind.png", "Broad Oklahoma W--E wind"),
    ("seok_wind.png", "SE Oklahoma corridor wind"),
]:
    p = fig(name)
    if p:
        wind_figs.append({"path": p, "caption": cap})

if wind_figs:
    rb.add_figure_grid(s3_2, wind_figs,
        caption="Wind speed cross-sections showing boundary layer wind structure",
        ncols=2, label="fig:wind_grid")

# --- 3.3 Relative Humidity ---
s3_3 = rb.add_section("Relative Humidity Structure", r"""
RH cross-sections reveal the vertical extent of the dry column.
Values below 15\% (red flag threshold) shown across the depth of the boundary layer.""", level=2)

rh_figs = []
for name, cap in [
    ("newalla_we_rh.png", "W--E RH through Newalla"),
    ("newalla_swne_rh.png", "SW--NE RH along spread axis"),
    ("okc_ns_rh.png", "N--S RH through OKC"),
    ("oklahoma_we_rh.png", "Broad Oklahoma W--E RH"),
    ("seok_rh.png", "SE Oklahoma corridor RH"),
]:
    p = fig(name)
    if p:
        rh_figs.append({"path": p, "caption": cap})

if rh_figs:
    rb.add_figure_grid(s3_3, rh_figs,
        caption="Relative humidity cross-sections showing dry column depth",
        ncols=2, label="fig:rh_grid")

# --- 3.4 Isentropic Ascent ---
s3_4 = rb.add_section("Isentropic Ascent Analysis", r"""
The new isentropic ascent product shows RH shading with omega (vertical velocity)
contours: blue = ascent, red dashed = descent. Purple zones highlight moist ascent
regions (RH $>$ 70\% with upward motion). Thin colored contours show the
geostrophic wind perpendicular to the section (jet position). This analysis reveals
whether any moisture return or precipitation is possible to moderate fire conditions.""", level=2)

isen_figs = []
for name, cap in [
    ("newalla_we_isentropic_ascent.png", "W--E isentropic ascent through Newalla"),
    ("newalla_swne_isentropic_ascent.png", "SW--NE isentropic ascent along fire axis"),
    ("okc_ns_isentropic_ascent.png", "N--S isentropic ascent through OKC metro"),
    ("oklahoma_we_isentropic_ascent.png", "Broad Oklahoma W--E isentropic ascent"),
    ("seok_isentropic_ascent.png", "SE Oklahoma corridor isentropic ascent"),
]:
    p = fig(name)
    if p:
        isen_figs.append({"path": p, "caption": cap})

if isen_figs:
    rb.add_figure_grid(s3_4, isen_figs,
        caption="Isentropic ascent analysis showing vertical motion and moisture interaction",
        ncols=2, label="fig:isen_grid")

# --- 3.5 VPD ---
s3_5 = rb.add_section("Vapor Pressure Deficit", r"""
VPD measures the drying power of the atmosphere --- higher values indicate more
aggressive fuel desiccation. Values above 30 hPa indicate extreme fire danger.""", level=2)

vpd_figs = []
for name, cap in [
    ("newalla_we_vpd.png", "W--E VPD through Newalla"),
    ("newalla_swne_vpd.png", "SW--NE VPD along fire axis"),
    ("okc_ns_vpd.png", "N--S VPD through OKC metro"),
    ("oklahoma_we_vpd.png", "Broad Oklahoma W--E VPD"),
    ("seok_vpd.png", "SE Oklahoma corridor VPD"),
]:
    p = fig(name)
    if p:
        vpd_figs.append({"path": p, "caption": cap})

if vpd_figs:
    rb.add_figure_grid(s3_5, vpd_figs,
        caption="Vapor pressure deficit showing atmospheric drying intensity",
        ncols=2, label="fig:vpd_grid")

# --- 3.6 Additional Products ---
s3_6 = rb.add_section("Additional Atmospheric Products", r"""
Temperature, omega (vertical velocity), dewpoint depression, lapse rate, theta-e,
and moisture transport provide deeper insight into the fire environment.""", level=2)

extra_figs = []
for name, cap in [
    ("newalla_we_temp.png", "Temperature (Newalla W--E)"),
    ("newalla_we_omega.png", "Omega/vertical velocity (Newalla W--E)"),
    ("newalla_we_dewpoint_dep.png", "Dewpoint depression (Newalla W--E)"),
    ("newalla_we_lapse.png", "Lapse rate (Newalla W--E)"),
    ("newalla_we_theta_e.png", "Theta-e (Newalla W--E)"),
    ("newalla_we_moisture.png", "Moisture transport (Newalla W--E)"),
    ("oklahoma_we_temp.png", "Temperature (Oklahoma W--E)"),
    ("oklahoma_we_omega.png", "Omega (Oklahoma W--E)"),
    ("oklahoma_we_dewpoint_dep.png", "Dewpoint depression (Oklahoma W--E)"),
    ("oklahoma_we_lapse.png", "Lapse rate (Oklahoma W--E)"),
    ("oklahoma_we_theta_e.png", "Theta-e (Oklahoma W--E)"),
    ("oklahoma_we_isentropic_ascent.png", "Isentropic ascent (Oklahoma W--E)"),
]:
    p = fig(name)
    if p:
        extra_figs.append({"path": p, "caption": cap})

if extra_figs:
    # Show in 2-column grids, 4 at a time
    for i in range(0, len(extra_figs), 4):
        batch = extra_figs[i:i+4]
        rb.add_figure_grid(s3_6, batch,
            caption=f"Additional atmospheric products ({i+1}--{i+len(batch)})",
            ncols=2, label=f"fig:extra_{i}")

# ══════════════════════════════════════════════════════════════════════
# Section 4: Fire Risk Scoring
# ══════════════════════════════════════════════════════════════════════
s4 = rb.add_section("Fire Risk Scoring", content=
r"""Quantitative fire risk scores (0--100) computed from HRRR atmospheric data
along each transect. Scores integrate wind speed, RH, VPD, temperature anomaly,
and fuel moisture indicators. Scores above 50 indicate HIGH risk; above 70 is EXTREME.""")

def parse_fire_risk(txt):
    """Parse fire_risk.txt into list of dicts with transect name + JSON data."""
    import re
    results = []
    blocks = re.split(r'===\s*FIRE RISK:\s*', txt)
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        # First line: transect name ===
        lines = block.split('\n', 1)
        name = lines[0].replace('===', '').strip()
        if len(lines) > 1:
            json_str = lines[1].strip()
            if json_str:
                try:
                    data = json.loads(json_str)
                    data['transect'] = name
                    results.append(data)
                except json.JSONDecodeError:
                    pass
    return results

if fire_risk_txt:
    hrrr_risks = parse_fire_risk(fire_risk_txt)
    if hrrr_risks:
        s4_1 = rb.add_section("HRRR Fire Risk Scores", r"""
Fire risk scores computed from HRRR cross-section data along each transect.
Note: Scores integrate the full vertical column, which can dilute extreme
surface conditions (e.g., surface RH of 11--15\% averaged with 40--50\% RH
aloft produces misleadingly low scores). Surface observations confirm
conditions are far more dangerous than column-averaged scores suggest.""", level=2)
        risk_rows = []
        for r in hrrr_risks:
            factors = ', '.join(r.get('contributing_factors', []))
            rh = r.get('rh_stats', {})
            wind = r.get('wind_stats', {})
            risk_rows.append([
                esc(r.get('transect', '?')),
                str(r.get('risk_score', '?')),
                r.get('risk_level', '?'),
                f"{rh.get('min', '?'):.0f}--{rh.get('max', '?'):.0f}" if isinstance(rh.get('min'), (int, float)) else '?',
                f"{wind.get('max', '?'):.1f}" if isinstance(wind.get('max'), (int, float)) else '?',
                esc(factors),
            ])
        rb.add_table(s4_1,
            caption="HRRR fire risk scores by transect. Scores 0--100 (column-averaged). Surface conditions are significantly worse than column scores indicate.",
            headers=["Transect", "Score", "Level", r"RH Range (\%)", "Max Wind (m/s)", "Factors"],
            rows=risk_rows,
            label="tab:hrrr_risk"
        )
    else:
        rb.add_section("HRRR Fire Risk Scores", r"Fire risk data could not be parsed.", level=2)

def parse_gfs_fire_risk(txt):
    """Parse GFS plain-text fire risk into list of dicts."""
    import re
    results = []
    # Split on numbered entries like "1. NEWALLA TRANSECT ..."
    blocks = re.split(r'\n\d+\.\s+', txt)
    for block in blocks:
        block = block.strip()
        if not block or 'Risk Score' not in block:
            continue
        lines = block.split('\n')
        name = lines[0].split('(')[0].strip()
        data = {'transect': name}
        for line in lines:
            line = line.strip()
            m = re.match(r'Risk Score:\s*(\d+)', line)
            if m:
                data['risk_score'] = int(m.group(1))
            m = re.match(r'Risk Level:\s*(\w+)', line)
            if m:
                data['risk_level'] = m.group(1)
            m = re.match(r'Contributing Factors:\s*(.*)', line)
            if m:
                data['factors'] = m.group(1)
            m = re.match(r'RH Stats:.*min=([\d.]+)%.*max=([\d.]+)%', line)
            if m:
                data['rh_min'] = float(m.group(1))
                data['rh_max'] = float(m.group(2))
        results.append(data)
    return results

if gfs_risk_txt:
    gfs_risks = parse_gfs_fire_risk(gfs_risk_txt)
    if gfs_risks:
        s4_2 = rb.add_section("GFS Extended Fire Risk", r"""
GFS-based fire risk scores for extended outlook. Same column-averaging
caveats apply --- surface conditions are more extreme than scores suggest.""", level=2)
        gfs_rows = []
        for r in gfs_risks:
            rh_range = f"{r.get('rh_min', '?'):.0f}--{r.get('rh_max', '?'):.0f}" if 'rh_min' in r else '?'
            gfs_rows.append([
                esc(r.get('transect', '?')),
                str(r.get('risk_score', '?')),
                r.get('risk_level', '?'),
                rh_range,
                esc(r.get('factors', '')),
            ])
        rb.add_table(s4_2,
            caption="GFS extended fire risk scores by transect.",
            headers=["Transect", "Score", "Level", r"RH Range (\%)", "Factors"],
            rows=gfs_rows,
            label="tab:gfs_risk"
        )
    else:
        rb.add_section("GFS Extended Fire Risk", r"GFS fire risk data could not be parsed.", level=2)

# ══════════════════════════════════════════════════════════════════════
# Section 5: Temporal Evolution (HRRR Forecast)
# ══════════════════════════════════════════════════════════════════════
s5 = rb.add_section("Temporal Evolution: HRRR Forecast", content=
r"""HRRR cross-sections at multiple forecast hours show how fire weather conditions
evolve through the evening and overnight. Key concerns: evening wind shift,
overnight low-level jet loading, and whether any humidity recovery occurs.""")

# Fire wx temporal
fhr_fire_figs = []
for fhr in ['00', '03', '06', '09', '12', '15']:
    p = fig(f"newalla_fhr{fhr}_fire_wx.png")
    if p:
        fhr_fire_figs.append({"path": p, "caption": f"F{fhr} fire weather"})

if fhr_fire_figs:
    rb.add_figure_grid(s5, fhr_fire_figs[:6],
        caption="Newalla fire weather composite: temporal evolution (HRRR 21Z cycle)",
        ncols=3 if len(fhr_fire_figs) >= 3 else 2, label="fig:temporal_fire")

# Wind temporal
fhr_wind_figs = []
for fhr in ['00', '03', '06', '09', '12', '15']:
    p = fig(f"newalla_fhr{fhr}_wind.png")
    if p:
        fhr_wind_figs.append({"path": p, "caption": f"F{fhr} wind speed"})

if fhr_wind_figs:
    rb.add_figure_grid(s5, fhr_wind_figs[:6],
        caption="Newalla wind speed: temporal evolution",
        ncols=3 if len(fhr_wind_figs) >= 3 else 2, label="fig:temporal_wind")

# RH temporal
fhr_rh_figs = []
for fhr in ['00', '03', '06', '09', '12', '15']:
    p = fig(f"newalla_fhr{fhr}_rh.png")
    if p:
        fhr_rh_figs.append({"path": p, "caption": f"F{fhr} RH"})

if fhr_rh_figs:
    rb.add_figure_grid(s5, fhr_rh_figs[:6],
        caption="Newalla relative humidity: temporal evolution",
        ncols=3 if len(fhr_rh_figs) >= 3 else 2, label="fig:temporal_rh")

# OKC N-S temporal
okc_temp_figs = []
for fhr in ['00', '06', '12']:
    for prod, label in [('fire_wx', 'fire wx'), ('wind', 'wind')]:
        p = fig(f"okc_ns_fhr{fhr}_{prod}.png")
        if p:
            okc_temp_figs.append({"path": p, "caption": f"OKC N--S F{fhr} {label}"})

if okc_temp_figs:
    rb.add_figure_grid(s5, okc_temp_figs,
        caption="OKC metro N--S temporal evolution",
        ncols=2, label="fig:temporal_okc")


# ══════════════════════════════════════════════════════════════════════
# Section 6: GFS Extended Outlook
# ══════════════════════════════════════════════════════════════════════
s6 = rb.add_section("GFS Extended-Range Outlook", content=
r"""GFS 0.25$^\circ$ cross-sections provide a multi-day outlook for fire weather
conditions. Key question: when does the pattern break and moisture return?""")

# GFS fire wx at different lead times
gfs_fire_figs = []
for fhr in ['06', '24', '48', '72']:
    p = fig(f"gfs_newalla_fhr{fhr}_fire_wx.png")
    if p:
        gfs_fire_figs.append({"path": p, "caption": f"GFS F{fhr} fire weather"})

if gfs_fire_figs:
    rb.add_figure_grid(s6, gfs_fire_figs,
        caption="GFS extended fire weather outlook: Newalla transect",
        ncols=2, label="fig:gfs_fire")

gfs_rh_figs = []
for fhr in ['06', '24', '48', '72']:
    p = fig(f"gfs_newalla_fhr{fhr}_rh.png")
    if p:
        gfs_rh_figs.append({"path": p, "caption": f"GFS F{fhr} RH"})

if gfs_rh_figs:
    rb.add_figure_grid(s6, gfs_rh_figs,
        caption="GFS extended RH outlook: moisture recovery timeline",
        ncols=2, label="fig:gfs_rh")

# Broader OK GFS
gfs_ok_figs = []
for fhr in ['06', '24', '48', '72']:
    for prod, label in [('fire_wx', 'fire wx'), ('rh', 'RH'), ('wind_speed', 'wind')]:
        p = fig(f"gfs_oklahoma_fhr{fhr}_{prod}.png")
        if p:
            gfs_ok_figs.append({"path": p, "caption": f"GFS OK F{fhr} {label}"})

if gfs_ok_figs:
    for i in range(0, len(gfs_ok_figs), 4):
        batch = gfs_ok_figs[i:i+4]
        rb.add_figure_grid(s6, batch,
            caption=f"GFS broader Oklahoma outlook ({i+1}--{i+len(batch)})",
            ncols=2, label=f"fig:gfs_ok_{i}")


# ══════════════════════════════════════════════════════════════════════
# Section 8: Forecast & Operational Outlook
# ══════════════════════════════════════════════════════════════════════
s8 = rb.add_section("Forecast and Operational Outlook", content=
r"""
\subsection{Immediate Concerns (Next 6 Hours)}
\begin{itemize}[leftmargin=2em]
\item \textbf{Continued extreme fire spread:} SW winds 15--25 kt with gusts to 25 kt, RH 11--15\%
\item \textbf{RH still crashing:} KOKC dropped 20\%$\rightarrow$14\%, KPWA 14\%$\rightarrow$11\% in past 3 hours
\item \textbf{Dewpoints falling:} Down 3--6°F in 3 hours --- dry air advection continuing
\item \textbf{Wind-driven runs:} All active fires spreading NE toward populated areas
\item \textbf{New ignitions:} Extreme conditions support rapid ignition from any source (I-40 corridor, powerlines, equipment)
\end{itemize}

\subsection{Evening Transition (6--12 Hours)}
""" + rb.add_alert_box(
    r"FRONTAL WIND SHIFT: Cold front passage expected 03--09Z (9 PM -- 3 AM CST). "
    r"Winds will shift from S/SSW 12--22 kt to N/NNW 12--25 kt (gusts to 25 kt). "
    r"This converts ALL current south flanks into new headfires running south. "
    r"Low-level wind shear: 40--45 kt from 220--240° at 2000 ft AGL noted in TAFs. "
    r"This is the MOST DANGEROUS period for active fires.",
    color="red", title=r"CRITICAL: WIND SHIFT WARNING"
) + r"""
\begin{itemize}[leftmargin=2em]
\item \textbf{Wind shift timing:} Frontal passage 03--09Z tonight (from TAF analysis)
\item \textbf{Pre-frontal:} S/SSW 12--22 kt --- fires spreading N/NE
\item \textbf{Post-frontal:} N/NNW 12--25 kt gusting 25 kt --- fires reverse, all south flanks become headfires
\item \textbf{Low-level jet:} 40--45 kt at 2000 ft AGL from 220--240° (pre-frontal LLJ loading)
\item \textbf{Humidity recovery:} Uncertain --- cold front may not bring significant moisture
\item \textbf{Falling pressures:} 0.06--0.10 inHg drop in 3 hours confirms approaching front
\end{itemize}

\subsection{Extended (24--72 Hours)}
\begin{itemize}[leftmargin=2em]
\item \textbf{Pattern persistence:} GFS indicates continued dry/warm anomaly for 24--48h
\item \textbf{Cold front timing:} Full pattern change and moisture return timeline
  shown in GFS extended outlook section
\item \textbf{Rekindle risk:} Even if winds diminish, low RH can sustain smoldering
  fires that rekindle with next wind event
\end{itemize}

\subsection{Areas of Greatest Concern for New Fire Starts}
\begin{itemize}[leftmargin=2em]
\item \textbf{SE OKC corridor} (Newalla, Draper, Choctaw, Harrah) --- active fires + WUI
\item \textbf{Rural grasslands} E/SE of OKC --- continuous fine fuels, limited access
\item \textbf{I-40 corridor} --- human ignition sources + extreme spread conditions
\item \textbf{Any area downwind} of existing fires during wind shifts
\end{itemize}
""")

# ══════════════════════════════════════════════════════════════════════
# Section 9: Data Sources & Methods
# ══════════════════════════════════════════════════════════════════════
s9 = rb.add_section("Data Sources and Methods", content=r"""
\begin{itemize}[leftmargin=2em]
\item \textbf{HRRR:} 3-km horizontal resolution, 21Z cycle, FHR 00--15 (15-hour forecast window)
\item \textbf{GFS:} 0.25$^\circ$ ($\sim$28 km), 12Z cycle, FHR 6--384 (extended outlook to 16 days)
\item \textbf{Cross-sections:} 5 transects $\times$ 5+ products per transect = 25+ static images
\item \textbf{Temporal evolution:} 6 forecast hours $\times$ 3 products = 18 temporal frames + 4 animated GIFs
\item \textbf{GFS extended:} 2 transects $\times$ 4 FHRs $\times$ 3 products = 24 GFS images + 2 GIFs
\item \textbf{Surface obs:} METAR from 10 Oklahoma stations via aviationweather.gov
\item \textbf{Fire weather intel:} NWS alerts (OUN, TSA, AMA), SPC fire weather outlook, NIFC
\item \textbf{Street View:} 12 Google Street View images of fire-affected areas
\item \textbf{Fire risk scoring:} wxsection.com fire risk algorithm (0--100 scale)
\item \textbf{Isentropic ascent:} New analysis product showing RH + omega + geostrophic wind
\item \textbf{Report generation:} 7 parallel AI agents, compiled via wxsection.com ReportBuilder
\end{itemize}

\subsection{Products Generated}
""" + r"""
\begin{verbatim}
""" + f"Total figures: {len(figs_matching('*.png'))} PNG + {len(figs_matching('*.jpg'))} JPG + {len(figs_matching('*.gif'))} GIF" + r"""
\end{verbatim}
""")

# ══════════════════════════════════════════════════════════════════════
# Compile PDF
# ══════════════════════════════════════════════════════════════════════
print(f"\n{'='*60}")
print(f"Figures available: {len(figs_matching('*.png'))} PNG, {len(figs_matching('*.jpg'))} JPG, {len(figs_matching('*.gif'))} GIF")
print(f"Intel files: NWS={'yes' if nws_intel else 'no'}, Obs={'yes' if surface_obs else 'no'}, Web={'yes' if web_intel else 'no'}")
print(f"{'='*60}\n")

rb.compile_pdf(passes=2)
print(f"\nDone! PDF at: {os.path.join(OUT_DIR, 'main.pdf')}")
