r"""
Build Amarillo WUI Fire PDF report.
Run: cd C:/Users/drew/hrrr-maps && python research/amarillo_wui_report/build_pdf.py
"""
import sys, os, glob
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from tools.agent_tools.report_builder import ReportBuilder, ReportConfig

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
FIG_DIR = os.path.join(OUT_DIR, "figures")
SV_DIR = os.path.join(OUT_DIR, "streetview")
os.chdir(OUT_DIR)

config = ReportConfig(
    title="Amarillo Lake WUI Fire: Operational Intelligence Report",
    author="wxsection.com AI Agent Swarm",
    date="February 9, 2026 --- 21:00 UTC (3:00 PM CST)",
    report_type="forecast",
    institution="wxsection.com",
)

rb = ReportBuilder(config, output_dir=OUT_DIR)

rb.set_abstract(
    "A wildland-urban interface fire originating near Amarillo Lake has jumped "
    "West Amarillo Boulevard and is threatening residential neighborhoods in "
    "northwest Amarillo, TX. North Heights High School has been evacuated with "
    "students bused to other campuses. Amarillo PD has blocked traffic on North "
    "Hughes Street. Surface winds are sustained at 19 kt gusting to 30-33 kt "
    "from the southwest (230 deg) with relative humidity at 10% and temperatures "
    "76 deg F --- 25 deg F above normal for February. The SPC has this area under "
    "a CRITICAL fire weather outlook. Three NWS Red Flag Warnings are active "
    "covering the Texas Panhandle. HRRR cross-section analysis shows a deep dry "
    "column with no moisture at any level and a 700 hPa low-level jet providing "
    "the momentum source for surface gusts. The nocturnal low-level jet will "
    "load overnight with no RH recovery, creating continued risk. This report "
    "was generated by 3 parallel AI agents using HRRR 3-km, GFS 0.25 deg, "
    "Google Street View, NWS/SPC alerts, and METAR observations."
)

# ══════════════════════════════════════════════════════════════════════════
# Section 1: Situation Overview
# ══════════════════════════════════════════════════════════════════════════
s1 = rb.add_section("Situation Overview", content=
rb.add_alert_box(
    "WILDLAND-URBAN INTERFACE FIRE: Fire has jumped West Amarillo Boulevard "
    "and is spreading NE into residential neighborhoods. North Heights High "
    "School evacuated. North Hughes Street blocked by APD. Active fire under "
    "SPC CRITICAL conditions with 10% RH and 30+ kt gusts.",
    color="red", title="WUI FIRE ALERT"
) + r"""

\subsection{Fire Location and Status}
\begin{itemize}[leftmargin=2em]
\item \textbf{Origin:} Amarillo Lake, near North Hughes St / NW 5th Ave (35.21$^\circ$N, 101.845$^\circ$W)
\item \textbf{Jump point:} Fire has crossed West Amarillo Boulevard heading NE
\item \textbf{Wind-driven spread:} SW at 230$^\circ$, 19~kt sustained, gusts 30--33~kt $\rightarrow$ fire spreading \textbf{NE into residential areas}
\item \textbf{Evacuations:} North Heights High School --- students bused to other campuses
\item \textbf{Road closures:} N Hughes St at W Amarillo Blvd blocked by APD motorcycle officers
\item \textbf{Source:} MyHighPlains.com confirmed AFD response at 1:40 PM CST
\end{itemize}

\subsection{Active NWS Alerts}
\begin{itemize}[leftmargin=2em]
\item \textbf{Red Flag Warning} (NWS Amarillo) --- TX/OK Panhandles including \textbf{Potter County} (Amarillo). SW 20--25 mph, gusts \textbf{40 mph}. RH as low as \textbf{7\%}. Temps 70s--80s$^\circ$F. ERC 70th--89th percentile. Fire Environment 6/10. Until 7 PM CST.
\item \textbf{Red Flag Warning} (NWS Lubbock) --- SW TX Panhandle. SW 20--25 mph, gusts 35 mph. RH 9\%. Until 7 PM CST.
\item \textbf{SPC Day 1 CRITICAL} fire weather outlook covers the entire TX Panhandle.
\end{itemize}""")

# ══════════════════════════════════════════════════════════════════════════
# Section 2: Current Conditions
# ══════════════════════════════════════════════════════════════════════════
s2 = rb.add_section("Current Surface Conditions", content=
r"""Latest METAR observation from Amarillo International Airport (KAMA), 8 km SE of the fire:""")

rb.add_table(s2,
    caption="KAMA METAR at 2053 UTC (2:53 PM CST), February 9, 2026",
    headers=["Parameter", "Value", "Assessment"],
    rows=[
        ["Wind", "230 deg / 19 kt G30 kt", "CRITICAL (SW, driving fire NE)"],
        ["Peak Gust", "33 kt (38 mph) at 2030Z", "Exceeds RFW threshold"],
        ["Temperature", "24.4C (76F)", "25F above Feb normal"],
        ["Dewpoint", "-8.9C (16F)", "Extreme dryness"],
        ["RH (est.)", "~10%", "CRITICAL (below 13% RFW)"],
        ["Visibility", "10+ SM", "Clear --- no precip possible"],
        ["Altimeter", "29.99 inHg", "Falling (trough approach)"],
        ["SLP", "1012.6 mb", "Down from 1016 earlier"],
        ["Sky", "CLR", "Full solar heating"],
    ],
    label="tab:metar",
)

s2a = rb.add_section("Conditions Trend", level=2, content=
r"""\begin{itemize}[leftmargin=2em]
\item \textbf{Pressure falling:} SLP dropped from 1016$\rightarrow$1013 mb in 3 hours --- deepening trough driving wind acceleration
\item \textbf{Wind steady:} Sustained 19--22~kt with gusts 30--35~kt since 19Z. No relaxation expected until after 01Z (7 PM CST).
\item \textbf{RH bottoming:} 10--11\% --- at or near diurnal minimum. Will recover slightly after sunset but \textbf{stay below 25\% overnight} per HRRR.
\item \textbf{Wind shift approaching:} Clines Corners NM (upwind) already showing WNW 300$^\circ$. When this cold front reaches Amarillo ($\sim$06Z / midnight), winds shift to N/NW --- \textbf{fire flanks become new head}.
\end{itemize}""")

# ══════════════════════════════════════════════════════════════════════════
# Section 3: HRRR Cross-Section Analysis
# ══════════════════════════════════════════════════════════════════════════
s3 = rb.add_section("HRRR Cross-Section Analysis", content=
r"""Cross-sections from the HRRR 3-km model (latest available cycle) through the Amarillo fire zone. Two primary transects: (1) W--E at 35.21$^\circ$N from 102.5$^\circ$W to 101.2$^\circ$W, covering the upwind terrain through Amarillo to downwind areas; (2) SW--NE from 35.15$^\circ$N/102$^\circ$W to 35.35$^\circ$N/101.6$^\circ$W, aligned with the wind-driven fire spread direction.""")

# Add figures - check what exists
fig_order = [
    ("ama_firewx_swne.png", "Fire Weather Composite, SW-NE through fire zone aligned with wind direction (230 deg). Cross-hatching shows extreme low RH extending through the full boundary layer. This is the fire's spread corridor."),
    ("ama_wind_swne.png", "Wind Speed, SW-NE through fire zone. Shows the low-level momentum driving fire spread from the origin toward residential neighborhoods NE of Amarillo Blvd."),
    ("ama_rh_swne.png", "Relative Humidity, SW-NE through fire zone. The entire troposphere below 500 hPa is desiccated --- uniformly below 20% RH with no moisture source at any level."),
    ("ama_firewx_we.png", "Fire Weather Composite, W-E through Amarillo at 35.21N. Deep red/cross-hatched from surface through 500 hPa across the entire transect. Terrain slopes downward from west, enhancing downslope drying and wind acceleration."),
    ("ama_wind_we.png", "Wind Speed, W-E through Amarillo. Surface winds 15-25 kt with a 700 hPa low-level jet at 30-40 kt providing the momentum source. The jet mixes down to the surface during afternoon heating."),
    ("ama_rh_we.png", "Relative Humidity, W-E through Amarillo. Bone dry through the entire column --- no level shows RH above 30%. Zero chance of precipitation or meaningful humidity recovery."),
    ("ama_temp_we.png", "Temperature, W-E through Amarillo. Surface temperatures 18-24C (65-76F). 0C isotherm near 630 hPa. Warm for February --- enhancing fire behavior."),
]

for fname, caption in fig_order:
    fpath = os.path.join(FIG_DIR, fname)
    if os.path.isfile(fpath):
        rb.add_figure(s3, fpath, caption, label=f"fig:{fname.replace('.png','')}")

# Isentropic analysis
s3b = rb.add_section("Isentropic Analysis (Downslope Dynamics)", level=2, content=
r"""Isentropic cross-sections reveal the downslope wind mechanics driving this fire. The Y-axis shows potential temperature ($\theta$) surfaces with pressure contoured as overlays. Compressed isentropes indicate acceleration; widely-spaced isentropes indicate stability.""")

isen_figs = [
    ("ama_isen_wind_we.png", "Isentropic Wind Speed. Strong wind maximum at 310-320K theta levels. Compressed isentropes near the terrain break show classic downslope acceleration --- momentum transfers from the mountain crest onto the High Plains."),
    ("ama_isen_rh_we.png", "Isentropic RH. Dry air on all theta surfaces from 300K to 320K. The low-level isentropic surfaces show the mechanism: dry air from above the terrain crest descends adiabatically, warming and drying as it flows onto the plains."),
]

for fname, caption in isen_figs:
    fpath = os.path.join(FIG_DIR, fname)
    if os.path.isfile(fpath):
        rb.add_figure(s3b, fpath, caption)

# N-S transect
ns_path = os.path.join(FIG_DIR, "ama_wind_ns.png")
if os.path.isfile(ns_path):
    s3c = rb.add_section("N-S Transect (Wind Shift Approach)", level=2)
    rb.add_figure(s3c, ns_path,
        "Wind Speed, N-S through Amarillo at 101.845W (35.5N to 34.9N). "
        "Shows the wind field structure that the approaching cold front will modify. "
        "When the front arrives, northerly winds will replace the current southwesterly flow, "
        "causing the fire's southern flank to become the new head.")

# ══════════════════════════════════════════════════════════════════════════
# Section 4: Temporal Evolution
# ══════════════════════════════════════════════════════════════════════════
s4 = rb.add_section("Temporal Evolution", content=
r"""HRRR forecast sequence showing how fire weather conditions evolve at Amarillo over the next 12 hours.""")

temporal_figs = []
for fhr in [0, 3, 6, 9, 12]:
    fname = f"ama_firewx_fhr{fhr:02d}.png"
    fpath = os.path.join(FIG_DIR, fname)
    if os.path.isfile(fpath):
        hours_from_now = fhr
        temporal_figs.append({"path": fpath, "caption": f"FHR {fhr:02d} (+{fhr}h)"})

if len(temporal_figs) >= 4:
    rb.add_figure_grid(s4, temporal_figs[:4],
        caption="Fire weather composite evolution at Amarillo (W-E transect). "
                "Conditions remain critical through FHR 06 (evening), then the nocturnal "
                "LLJ develops. No meaningful RH recovery overnight.",
        ncols=2, label="fig:temporal-grid")
if len(temporal_figs) > 4:
    rb.add_figure(s4, temporal_figs[4]["path"],
        f"FHR 12: Overnight. LLJ loaded at 700-800 hPa with momentum ready to mix down at sunrise.",
        label="fig:temporal-fhr12")

# ══════════════════════════════════════════════════════════════════════════
# Section 5: GFS Extended Outlook
# ══════════════════════════════════════════════════════════════════════════
gfs_figs = sorted(glob.glob(os.path.join(FIG_DIR, "ama_gfs_*.png")))
if gfs_figs:
    s5 = rb.add_section("GFS Extended Forecast", content=
    r"""The GFS 0.25$^\circ$ model provides multi-day context beyond the HRRR 18-hour window, showing when genuine relief arrives.""")

    for fpath in gfs_figs:
        fname = os.path.basename(fpath)
        parts = fname.replace('.png','').split('_')
        product = parts[2] if len(parts) > 2 else ''
        fhr_str = parts[-1] if parts else ''
        fhr_num = fhr_str.replace('fhr','')
        pnames = {'firewx': 'Fire Wx', 'rh': 'RH', 'wind': 'Wind'}
        pname = pnames.get(product, product)
        try:
            fhr_int = int(fhr_num)
            valid_hr = 12 + fhr_int
            day_offset = valid_hr // 24
            hour = valid_hr % 24
            days = {0: 'Feb 9', 1: 'Feb 10', 2: 'Feb 11', 3: 'Feb 12'}
            caption = f"GFS {pname}, FHR {fhr_num} (valid {hour:02d}Z {days.get(day_offset, f'+{day_offset}d')})"
        except ValueError:
            caption = f"GFS {pname}"
        rb.add_figure(s5, fpath, caption, width="0.85\\textwidth")

# ══════════════════════════════════════════════════════════════════════════
# Section 6: Street View WUI Assessment
# ══════════════════════════════════════════════════════════════════════════
if os.path.isdir(SV_DIR):
    sv_files = sorted([f for f in os.listdir(SV_DIR) if f.endswith(('.jpg','.png'))])
    if sv_files:
        s6 = rb.add_section("Street View: WUI Fuel and Structure Assessment", content=
        r"""Ground-level imagery from Google Street View of the specific neighborhoods affected by the Amarillo Lake fire. These images show the wildland-urban interface conditions, fuel types, structure density, and vulnerability of the areas the fire is spreading into.""")

        sv_data = []
        for f in sv_files:
            name = f.replace('.jpg','').replace('.png','').replace('_',' ')
            # Remove leading numbers
            if name[0].isdigit():
                name = name.lstrip('0123456789').strip()
            sv_data.append({"path": os.path.join(SV_DIR, f), "caption": name.title()})

        for i in range(0, len(sv_data), 2):
            batch = sv_data[i:i+2]
            if len(batch) == 2:
                rb.add_figure_grid(s6, batch,
                    caption=f"WUI assessment: {batch[0]['caption']} / {batch[1]['caption']}",
                    ncols=2)
            else:
                rb.add_figure(s6, batch[0]['path'], batch[0]['caption'])

# ══════════════════════════════════════════════════════════════════════════
# Section 7: Forecast and Operational Outlook
# ══════════════════════════════════════════════════════════════════════════
s7 = rb.add_section("Forecast and Operational Outlook", content=
rb.add_alert_box(
    "WIND SHIFT WARNING: A cold front is approaching from the west. Clines Corners NM "
    "already shows WNW winds (300 deg) while Amarillo has SW (230 deg). When the front "
    "reaches Amarillo around midnight (06Z), winds will shift sharply to northerly. "
    "The fire's current southern flank will become the new head fire, potentially "
    "changing the threat axis from NE to SOUTH into previously unburned areas.",
    color="orange", title="CRITICAL WIND SHIFT APPROACHING"
) + r"""

\subsection{Timeline for Amarillo}
\begin{description}[leftmargin=2em]
\item[NOW -- 01Z (7 PM CST):] \textbf{Peak danger continues.} SW 19G30+~kt, 10\% RH. Fire will continue spreading NE. Any structures in the NE path are at immediate risk. Aggressive suppression critical before wind shift.
\item[01Z -- 06Z (7 PM -- midnight):] Winds remain elevated pre-frontally. Gradual temperature drop begins. \textbf{Window for establishing fire breaks on the southern flank before wind shift.}
\item[$\sim$06Z (midnight):] \textbf{Cold front passage.} Sharp wind shift to N/NW. Any uncontained southern perimeter becomes the new head. This is the most dangerous moment for fire behavior --- erratic gusts and rapid direction change.
\item[06Z -- 13Z (overnight):] Post-frontal northerly winds. Temperature drops. \textbf{But NO meaningful RH recovery} --- boundary layer stays 10--25\% even overnight. The nocturnal LLJ loads momentum at 700~hPa.
\item[After 16Z Feb 10 (10 AM CST):] Next-morning surge risk as loaded LLJ mixes down. If fire not contained, another extreme window.
\item[Mid-week:] Rain/storms return. Genuine relief.
\end{description}

\subsection{WUI Threat Assessment}
\begin{itemize}[leftmargin=2em]
\item \textbf{Primary threat axis (current):} SW$\rightarrow$NE through residential neighborhoods N/NE of W Amarillo Blvd
\item \textbf{Secondary threat axis (post-frontal):} N$\rightarrow$S as wind shift drives fire southward
\item \textbf{Urban fuels:} Dormant lawns, bare deciduous trees, vacant lots with weedy growth, wooden fencing
\item \textbf{Structure types at risk:} Single-family residential, commercial buildings along Amarillo Blvd corridor
\item \textbf{Critical infrastructure:} North Heights High School (evacuated), Amarillo Lake, N Hughes St corridor
\end{itemize}""")

# ══════════════════════════════════════════════════════════════════════════
# Section 8: Data Sources
# ══════════════════════════════════════════════════════════════════════════
s8 = rb.add_section("Data Sources", content=
r"""This report was generated by the wxsection.com AI Agent Research Platform using 3 parallel agents:
\begin{enumerate}[leftmargin=2em]
\item \textbf{Cross-Section Agent:} 15+ HRRR cross-sections (fire wx, wind, RH, temperature, isentropic, temporal), GIFs
\item \textbf{Street View + Web Intelligence Agent:} Google Street View of WUI impact zones, latest news
\item \textbf{GFS + Fire Risk Agent:} Extended-range GFS cross-sections, fire risk scores, NWS/SPC data
\end{enumerate}

\textbf{Models:} HRRR 3-km (latest cycle), GFS 0.25$^\circ$ (20260209 12Z). \\
\textbf{Observations:} KAMA METAR (2053Z). \\
\textbf{Alerts:} NWS api.weather.gov, SPC NOAA MapServer.""")

# ══════════════════════════════════════════════════════════════════════════
# Compile
# ══════════════════════════════════════════════════════════════════════════
print("Saving LaTeX...")
tex_path = rb.save_latex()
print(f"LaTeX saved: {tex_path}")

print("Compiling PDF...")
try:
    pdf_path = rb.compile_pdf(passes=2)
    print(f"\nSUCCESS: {pdf_path}")
    size_mb = os.path.getsize(pdf_path) / 1024 / 1024
    print(f"Size: {size_mb:.1f} MB")
except Exception as e:
    print(f"PDF compilation error: {e}")
    print("Check main.log for details. LaTeX source saved.")
